### ISSUE TITLE
TODO: General Features & Fixes

### ISSUE THREAD

**Issue by chrisfizik** [continuumizm/cizm-website#11]
- [x] remove admin from sitemap! g indexing!
- [ ] add site to eleventy list https://github.com/11ty/11ty-website/issues/new/choose
- [x] add eleventy generator tag https://github.com/11ty/eleventy/issues/1217
