### ISSUE TITLE
TODO: blog launch

### ISSUE THREAD

**Issue by chrisfizik** [continuumizm/cizm-website#7]
- [x] blog design article layout
- [x] migrate design to 11ty
- [x] homepage is just tagline and list of posts. expand to thumbs etc later
- [x] decide where to put social follow info (maybe leave in nav to start) 
- [x] move domain
- [x] add footer content somewhere

**Comment by chrisfizik** [comment]
- [x] add date published with time to post badge hover
- [x] adjust netlifycms to make only certain fields necessary 
- [x] remove localhost from analytics tracking
